# Generated by Django 4.0.8 on 2023-02-07 12:27

from django.db import migrations
import twotrickpony.pages.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_homepage_event_date_alter_homepage_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='thank_you_email_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('faq', twotrickpony.pages.blocks.AccordionBlock(child_block=wagtail.blocks.StructBlock([('titel', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock())])))], use_json_field=True),
        ),
    ]
